---
- hosts: webservers
  tasks:
  - name: make the file in /opt
    file:
      path: /opt/sshkey
      state: directory
      owner: root
      group: root
      mode: 0700
 
  - name: copy the file 
    copy:
      src: "/root/.ssh/id_rsa.pub"
      dest: "/opt/sshkey/id_rsa.pub"
      owner: root
      group: root
      mode: 0600
  
  - name: make the root directory
    file:
      path: /root/.ssh
      state: directory
      owner: root
      group: root
      mode: 0700
  
  - name: build the autherized key 
    assemble:
      src: "/opt/sshkey"
      dest: "/root/.ssh/authorized_keys"
      owner: root
      group: root
      mode: 0700
