---
- name: fetch ssh machine key
  hosts: sol
  tasks:
    - name: Fetch key
      slurp:
        src: /root/.ssh/id_rsa.pub
      register: sshkey
- name: Copy ssh key to all hosts
  hosts: all
  tasks:
    - name: make direcory to all
      file:
        state: directory
        path : /root/.ssh
        owner: root
        group: root
        mode: 0700
    - name: Install key
      copy:
        contents: "{{ hostvars.all.sshkey|b64decode }}" 
        dest: /root/.ssh/authorized_keys
        owner: root
        group: root
        mode: 0600
