--- 
- 
  hosts: webservers
  name: "Configure webserver with nginx"
  sudo: true
  tasks: 
    - 
      apt: "name=nginx update_cache=yes"
      name: "install nginx"
    - 
      copy: "src=files/nginx.conf dest=/etc/nginx/sites-available/default"
      name: "copy nginx config file"
    - 
      file: "dest=/etc/nginx/sites-enabled/default src=/etc/nginx/sites-available/default state=link\n"
      name: "enable configuration"
    - 
      name: "copy index.html"
      template: "src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644"
    - 
      name: "restart nginx"
      service: "name=nginx state=restarted"
